### ISSUE TITLE
Error after a long run (> 2months)

### ISSUE THREAD

**Issue by Congelli501** [jpillora/chisel#121]
Hi,
I have this error after 2 months of constant running:

2019/09/24 02:37:40 http: panic serving 10.39.0.0:41388: runtime error: invalid memory address or nil pointer dereference
goroutine 906693 [running]:
net/http.(*conn).serve.func1(0xc0002281e0)
	/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x7d38e0, 0xb52480)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/jpillora/chisel/server.(*Server).handleWebsocket(0xc0000b4600, 0x8b1fe0, 0xc0001a80e0, 0xc000862200)
	/src/server/handler.go:87 +0x47e
github.com/jpillora/chisel/server.(*Server).handleClientHandler(0xc0000b4600, 0x8b1fe0, 0xc0001a80e0, 0xc000862200)
	/src/server/handler.go:23 +0x40f
github.com/jpillora/chisel/server.(*Server).handleClientHandler-fm(0x8b1fe0, 0xc0001a80e0, 0xc000862200)
	/src/server/server.go:146 +0x48
net/http.HandlerFunc.ServeHTTP(0xc00009d450, 0x8b1fe0, 0xc0001a80e0, 0xc000862200)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.serverHandler.ServeHTTP(0xc0000a3110, 0x8b1fe0, 0xc0001a80e0, 0xc000862200)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0002281e0, 0x8b2360, 0xc0004fc480)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5

It seems to be coming from the internals of go...

**Comment by jpillora** [comment]
Thanks!
