### ISSUE TITLE
panic: ssh: no key material for msgNewKeys

### ISSUE THREAD

**Issue by xdtianyu** [jpillora/chisel#22]
Client get crashed after running about 3 minutes while the download speed is about `25MB/s`, I'm testing locally with `wget`.

System: ubuntu 16.04 64 bit (Linux desktop 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)

Desktop lan ip is `192.168.9.162`, port 80 is served by nginx for file download.

Server command: `chisel server -v --port 3000 --proxy http://example.com`

Client command: `chisel client -v --keepalive=10s http://192.168.9.162:3000 8001:80`

Download test command: `wget http://192.168.9.162:8001/dl/00002.m2ts`

chisel client crash log:
```
2017/02/03 20:50:39 client: Disconnected
2017/02/03 20:50:39 client: Fingerprint a4:59:fb:8a:fd:93:b5:0a:2e:08:9c:15:38:b3:1d:44
2017/02/03 20:50:39 client: Sending configurating
2017/02/03 20:50:39 client: Connected (Latency 333.839µs)
2017/02/03 20:50:42 client: 0.0.0.0:80#1: conn#4: Open
2017/02/03 20:51:24 client: Fingerprint a4:59:fb:8a:fd:93:b5:0a:2e:08:9c:15:38:b3:1d:44
2017/02/03 20:52:06 client: Fingerprint a4:59:fb:8a:fd:93:b5:0a:2e:08:9c:15:38:b3:1d:44
panic: ssh: no key material for msgNewKeys

goroutine 71 [running]:
panic(0x74ec60, 0xc820084bb0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
golang.org/x/crypto/ssh.(*connectionState).writePacket(0xc820128168, 0xc82011ad80, 0x7fc143dba330, 0xc8200126f0, 0xc8200e0440, 0x9, 0x9, 0x0, 0x0)
	/root/gocode/src/golang.org/x/crypto/ssh/transport.go:163 +0x2c5
golang.org/x/crypto/ssh.(*transport).writePacket(0xc820128100, 0xc8200e0440, 0x9, 0x9, 0x0, 0x0)
	/root/gocode/src/golang.org/x/crypto/ssh/transport.go:144 +0x81
golang.org/x/crypto/ssh.(*handshakeTransport).pushPacket(0xc820106140, 0xc8200e0440, 0x9, 0x9, 0x0, 0x0)
	/root/gocode/src/golang.org/x/crypto/ssh/handshake.go:206 +0x63
golang.org/x/crypto/ssh.(*handshakeTransport).kexLoop(0xc820106140)
	/root/gocode/src/golang.org/x/crypto/ssh/handshake.go:286 +0x40f
created by golang.org/x/crypto/ssh.newClientTransport
	/root/gocode/src/golang.org/x/crypto/ssh/handshake.go:113 +0x352
```

**Comment by jpillora** [comment]
I think it's about the download speed, can you retest with [rate-limited requests](http://unix.stackexchange.com/a/39219/42191)?

**Comment by jpillora** [comment]
Can't reproduce, if able - please reopen with more information
