### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xtqxk** [jpillora/chisel#370]
```
2022/06/30 09:36:28 http: panic serving 127.0.0.1:35814: runtime error: invalid memory address or nil pointer dereference
goroutine 2786 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1802 +0xb9
panic({0x7faa80, 0xba68b0})
        runtime/panic.go:1047 +0x266
github.com/jpillora/chisel/server.(*Server).handleWebsocket(0xc0000a8320, {0x8fff80, 0xc00019c460}, 0xc00010ae00)
        github.com/jpillora/chisel/server/server_handler.go:94 +0x463
github.com/jpillora/chisel/server.(*Server).handleClientHandler(0xc0000a8320, {0x8fff80, 0xc00019c460}, 0xc00010ae00)
        github.com/jpillora/chisel/server/server_handler.go:24 +0x129
net/http.HandlerFunc.ServeHTTP(0x0, {0x8fff80, 0xc00019c460}, 0x46204e)
        net/http/server.go:2047 +0x2f
net/http.serverHandler.ServeHTTP({0xc00037f860}, {0x8fff80, 0xc00019c460}, 0xc00010ae00)
        net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc00007c280, {0x9021a0, 0xc0000720c0})
        net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        net/http/server.go:3034 +0x4e8
```

**Comment by jpillora** [comment]
v1.12.0-rc1 fixes this exact panic — a client disconnecting between the SSH handshake and its config request produced a nil `*ssh.Request` and panicked the handler; it is now guarded, with a regression test reproducing this stack.

Please try out https://github.com/jpillora/chisel/releases/tag/v1.12.0-rc1 and report any issues in https://github.com/jpillora/chisel/issues/610
