### ISSUE TITLE
chisel crash randomly

### ISSUE THREAD

**Issue by magnww** [jpillora/chisel#405]
version: 1.8.1 linux amd64

chisel server -p 1111
chisel client 4.5.6.7:1111 1111:2222/udp

Client connect to server through a https proxy, and the network may not be stable.

```
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 13 [running]:
sync.(*WaitGroup).Wait(0x0?)
        sync/waitgroup.go:141 +0x85
github.com/jpillora/chisel/share/tunnel.(*waitGroup).Wait(...)
        github.com/jpillora/chisel/share/tunnel/wg.go:31
github.com/jpillora/chisel/share/tunnel.(*Tunnel).activatingConnWait.func1()
        github.com/jpillora/chisel/share/tunnel/tunnel.go:137 +0x2c
created by github.com/jpillora/chisel/share/tunnel.(*Tunnel).activatingConnWait
        github.com/jpillora/chisel/share/tunnel/tunnel.go:136 +0x85
```

**Comment by jpillora** [comment]
The `WaitGroup` panic reported here was fixed in v1.11.7 (#586). v1.12.0-rc1 additionally hardens the UDP path (idle flow sweep) and reconnect behavior, both of which this setup exercises.

Please try out https://github.com/jpillora/chisel/releases/tag/v1.12.0-rc1 and report any issues in https://github.com/jpillora/chisel/issues/610
